name: flutter_carousel_widget
description: A customizable carousel slider widget for Flutter, offering features such as infinite scrolling, auto-scrolling, custom child widgets, custom animations, pre-built indicators, expandable carousel widgets, and auto-sized child support.

version: 2.4.0

homepage: https://pub.dev/packages/flutter_carousel_widget
repository: https://github.com/nixrajput/flutter_carousel_widget
issue_tracker: https://github.com/nixrajput/flutter_carousel_widget/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.25.2
  lints: ^4.0.0
