name: flutter_carousel_widget
description: A customizable carousel slider widget in Flutter which supports infinite scrolling, auto scrolling, custom child widget, custom animations and built-in indicators.

version: 2.1.1

homepage: https://pub.dev/packages/flutter_carousel_widget
repository: https://github.com/nixrajput/flutter_carousel_widget
issue_tracker: https://github.com/nixrajput/flutter_carousel_widget/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.24.8
  lints: ^2.1.1
