name: Run Test Cases

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check_up_to_date:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history so we can compare

      - name: Fetch all branches
        run: git fetch origin

      - name: Check if branch is up-to-date with master
        run: |
          # Compare the current branch with the master branch
          if git merge-base --is-ancestor origin/master HEAD; then
            echo "The current branch is up-to-date with master."
          else
            echo "The current branch is not up-to-date with master."
            exit 1
          fi

  setup_and_test:
    name: Setup Flutter and Run Test Cases
    runs-on: ubuntu-latest
    needs: check_up_to_date
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.x

      - name: Run Flutter doctor
        run: flutter doctor -v

      - name: Run Flutter Analyzer (Lint)
        run: flutter analyze

      - name: Run Flutter Tests
        run: flutter test
